version: "3"

services:
  labelmultiplexservice:
    build: ./
    volumes:
      - ./src:/usr/src/app
    ports:
      - '8080:8080'
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'labels'
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      PGDATA: ./postgres-data
    ports:
      - '5432:5432'
    volumes_from:
        - data
      volumes:
        - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sq

  discoveryservice:
    image: springcloud/eureka
    ports:
      - "8761:8761"