spring:
  application:
    name: labelmultiplexer
  datasource:
    url: jdbc:postgresql://localhost:5432/labels
    username: postgres
    password: postgres
    platform: POSTGRESQL
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE