spring:
  profiles:
    include: default
  datasource:
    url: jdbc:postgresql://postgres:5432/labels
    username: postgres
    password: postgres
    platform: POSTGRESQL
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://discoveryservice:8761/eureka/
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream